import type { Metadata } from "next";
import { Geist, Geist_Mono, Titan_One } from "next/font/google"; // Import Titan_One
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define Titan_One font
const titanOne = Titan_One({
  weight: '400', // Titan One only has one weight
  subsets: ['latin'],
  variable: '--font-titan-one',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${titanOne.variable} antialiased`} // Add titanOne.variable
      >
        {children}
      </body>
    </html>
  );
}
